package com.gabow95k.keeply.presentation.shopping

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.EditText
import android.widget.Toast
import androidx.appcompat.app.AlertDialog
import androidx.core.view.isVisible
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.recyclerview.widget.ItemTouchHelper
import com.gabow95k.keeply.R
import com.gabow95k.keeply.data.local.db.KeeplyDatabase
import com.gabow95k.keeply.data.local.entity.ShoppingListEntity
import com.gabow95k.keeply.data.local.entity.ShoppingListItemEntity
import com.gabow95k.keeply.data.local.mapper.toDomain
import com.gabow95k.keeply.databinding.DialogAutoShoppingListBinding
import com.gabow95k.keeply.databinding.FragmentShoppingListsBinding
import com.gabow95k.keeply.domain.model.Category
import com.gabow95k.keeply.presentation.base.BaseFragment
import com.gabow95k.keeply.shopping.ShoppingListGenerator
import com.google.android.material.chip.Chip
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch

class ShoppingListsFragment : BaseFragment<FragmentShoppingListsBinding>() {

    private lateinit var listsAdapter: ShoppingListsAdapter
    private var swipeCallback: ShoppingListSwipeCallback? = null
    private var pendingOpenAutoDialog = false

    override fun inflateBinding(
        inflater: LayoutInflater,
        container: ViewGroup?
    ): FragmentShoppingListsBinding =
        FragmentShoppingListsBinding.inflate(inflater, container, false)

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        pendingOpenAutoDialog = arguments?.getBoolean(ARG_OPEN_AUTO) == true
        arguments?.remove(ARG_OPEN_AUTO)

        listsAdapter = ShoppingListsAdapter(
            onClick = { openList(it.id) },
            onEditClick = { showRenameDialog(it) },
            onDeleteClick = { confirmDeleteList(it) }
        )
        binding.rvLists.adapter = listsAdapter
        binding.fabCreate.setOnClickListener { showCreateOptions() }
        setupSwipe()
        observeLists()
    }

    private fun setupSwipe() {
        val revealWidth = resources.displayMetrics.density * 120f
        val callback = ShoppingListSwipeCallback(
            revealWidthPx = revealWidth,
            getForeground = { holder ->
                (holder as ShoppingListsAdapter.ViewHolder).binding.cardForeground
            }
        )
        swipeCallback = callback
        ItemTouchHelper(callback).attachToRecyclerView(binding.rvLists)
    }

    override fun onResume() {
        super.onResume()
        if (pendingOpenAutoDialog) {
            pendingOpenAutoDialog = false
            view?.post { showAutoGenerateDialog() }
        }
    }

    private fun observeLists() {
        val db = KeeplyDatabase.getInstance(requireContext())
        viewLifecycleOwner.lifecycleScope.launch {
            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
                combine(
                    db.shoppingListDao().observeAll(),
                    db.shoppingListDao().observeItemCounts()
                ) { lists, counts ->
                    val countMap = counts.associateBy { it.listId }
                    lists.map { entity ->
                        val count = countMap[entity.id]
                        val source = if (entity.sourceType == ShoppingListEntity.SOURCE_AUTO) {
                            getString(R.string.shopping_source_auto)
                        } else {
                            getString(R.string.shopping_source_manual)
                        }
                        ShoppingListUi(
                            id = entity.id,
                            name = entity.name,
                            meta = getString(
                                R.string.shopping_meta_pending,
                                count?.pendingCount ?: 0,
                                source
                            )
                        )
                    }
                }.collect { ui ->
                    listsAdapter.submitList(ui)
                    binding.tvEmpty.isVisible = ui.isEmpty()
                    binding.rvLists.isVisible = ui.isNotEmpty()
                }
            }
        }
    }

    private fun showCreateOptions() {
        AlertDialog.Builder(requireContext())
            .setTitle(R.string.shopping_create)
            .setItems(
                arrayOf(
                    getString(R.string.shopping_create_manual),
                    getString(R.string.shopping_create_auto)
                )
            ) { _, which ->
                if (which == 0) showManualCreateDialog() else showAutoGenerateDialog()
            }
            .show()
    }

    private fun showManualCreateDialog() {
        val input = EditText(requireContext()).apply {
            hint = getString(R.string.shopping_list_name)
            setText(R.string.shopping_list_name_default)
            setPadding(48, 32, 48, 32)
        }
        AlertDialog.Builder(requireContext())
            .setTitle(R.string.shopping_manual_title)
            .setView(input)
            .setPositiveButton(R.string.dialog_option_create) { _, _ ->
                val name = input.text?.toString()?.trim().orEmpty()
                if (name.isBlank()) {
                    Toast.makeText(
                        requireContext(),
                        R.string.shopping_error_name,
                        Toast.LENGTH_SHORT
                    )
                        .show()
                    return@setPositiveButton
                }
                createManualList(name)
            }
            .setNegativeButton(R.string.dialog_option_cancel, null)
            .show()
    }

    private fun showAutoGenerateDialog() {
        viewLifecycleOwner.lifecycleScope.launch {
            val categories = KeeplyDatabase.getInstance(requireContext())
                .categoryDao()
                .getAll()
                .map { it.toDomain() }
            if (!isAdded) return@launch
            presentAutoDialog(categories)
        }
    }

    private fun presentAutoDialog(categories: List<Category>) {
        val dialogBinding = DialogAutoShoppingListBinding.inflate(layoutInflater)
        dialogBinding.etListName.setText(R.string.shopping_list_name_auto_default)

        categories.forEach { category ->
            val chip = layoutInflater.inflate(
                R.layout.item_filter_chip,
                dialogBinding.chipGroupCategories,
                false
            ) as Chip
            chip.text = category.name
            chip.isChecked = true
            chip.tag = category.id
            dialogBinding.chipGroupCategories.addView(chip)
        }

        val dialog = AlertDialog.Builder(requireContext())
            .setTitle(R.string.shopping_auto_title)
            .setView(dialogBinding.root)
            .setPositiveButton(R.string.dialog_option_create, null)
            .setNegativeButton(R.string.dialog_option_cancel, null)
            .create()

        dialog.setOnShowListener {
            dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener {
                val name = dialogBinding.etListName.text?.toString()?.trim().orEmpty()
                if (name.isBlank()) {
                    dialogBinding.tilListName.error = getString(R.string.shopping_error_name)
                    return@setOnClickListener
                }
                val selectedCategories = mutableSetOf<Long>()
                for (i in 0 until dialogBinding.chipGroupCategories.childCount) {
                    val chip = dialogBinding.chipGroupCategories.getChildAt(i) as? Chip ?: continue
                    if (chip.isChecked) selectedCategories += chip.tag as Long
                }
                if (selectedCategories.isEmpty()) {
                    Toast.makeText(
                        requireContext(),
                        R.string.shopping_error_categories,
                        Toast.LENGTH_SHORT
                    ).show()
                    return@setOnClickListener
                }
                val out = dialogBinding.checkOutOfStock.isChecked
                val low = dialogBinding.checkLowStock.isChecked
                val expired = dialogBinding.checkExpired.isChecked
                if (!out && !low && !expired) {
                    Toast.makeText(
                        requireContext(),
                        R.string.shopping_error_criteria,
                        Toast.LENGTH_SHORT
                    ).show()
                    return@setOnClickListener
                }
                createAutoList(
                    name = name,
                    categoryIds = selectedCategories,
                    includeOutOfStock = out,
                    includeLowStock = low,
                    includeExpired = expired
                )
                dialog.dismiss()
            }
        }
        dialog.show()
    }

    private fun createManualList(name: String) {
        viewLifecycleOwner.lifecycleScope.launch {
            val db = KeeplyDatabase.getInstance(requireContext())
            val id = db.shoppingListDao().insert(
                ShoppingListEntity(
                    name = name,
                    sourceType = ShoppingListEntity.SOURCE_MANUAL
                )
            )
            Toast.makeText(requireContext(), R.string.shopping_created, Toast.LENGTH_SHORT).show()
            openList(id)
        }
    }

    private fun createAutoList(
        name: String,
        categoryIds: Set<Long>,
        includeOutOfStock: Boolean,
        includeLowStock: Boolean,
        includeExpired: Boolean
    ) {
        viewLifecycleOwner.lifecycleScope.launch {
            val db = KeeplyDatabase.getInstance(requireContext())
            val inventory = db.inventoryItemDao().observeAll().first()
            val generated = ShoppingListGenerator.generate(
                items = inventory,
                criteria = ShoppingListGenerator.Criteria(
                    categoryIds = categoryIds,
                    includeOutOfStock = includeOutOfStock,
                    includeLowStock = includeLowStock,
                    includeExpired = includeExpired
                )
            )
            if (generated.isEmpty()) {
                Toast.makeText(
                    requireContext(),
                    R.string.shopping_error_no_items,
                    Toast.LENGTH_SHORT
                ).show()
                return@launch
            }
            val listId = db.shoppingListDao().insert(
                ShoppingListEntity(
                    name = name,
                    sourceType = ShoppingListEntity.SOURCE_AUTO
                )
            )
            db.shoppingListItemDao().insertAll(
                generated.mapIndexed { index, item ->
                    ShoppingListItemEntity(
                        listId = listId,
                        name = item.name,
                        note = item.note,
                        inventoryItemId = item.inventoryItemId,
                        sortOrder = index
                    )
                }
            )
            Toast.makeText(requireContext(), R.string.shopping_created, Toast.LENGTH_SHORT).show()
            openList(listId)
        }
    }

    private fun openList(listId: Long) {
        swipeCallback?.closeOpenItem(binding.rvLists)
        parentFragmentManager.beginTransaction()
            .replace(R.id.fragmentContainer, ShoppingListDetailFragment.newInstance(listId))
            .addToBackStack(ShoppingListDetailFragment.TAG)
            .commit()
    }

    private fun showRenameDialog(list: ShoppingListUi) {
        swipeCallback?.closeOpenItem(binding.rvLists)
        val input = EditText(requireContext()).apply {
            setText(list.name)
            setSelection(list.name.length)
            setPadding(48, 32, 48, 32)
        }
        AlertDialog.Builder(requireContext())
            .setTitle(R.string.shopping_rename_title)
            .setView(input)
            .setPositiveButton(R.string.product_save) { _, _ ->
                val name = input.text?.toString()?.trim().orEmpty()
                if (name.isBlank()) {
                    Toast.makeText(
                        requireContext(),
                        R.string.shopping_error_name,
                        Toast.LENGTH_SHORT
                    )
                        .show()
                    return@setPositiveButton
                }
                renameList(list.id, name)
            }
            .setNegativeButton(R.string.dialog_option_cancel, null)
            .show()
    }

    private fun renameList(listId: Long, name: String) {
        viewLifecycleOwner.lifecycleScope.launch {
            val dao = KeeplyDatabase.getInstance(requireContext()).shoppingListDao()
            val entity = dao.getById(listId) ?: return@launch
            dao.update(
                entity.copy(
                    name = name,
                    updatedAt = System.currentTimeMillis()
                )
            )
            Toast.makeText(requireContext(), R.string.shopping_renamed, Toast.LENGTH_SHORT).show()
        }
    }

    private fun confirmDeleteList(list: ShoppingListUi) {
        swipeCallback?.closeOpenItem(binding.rvLists)
        AlertDialog.Builder(requireContext())
            .setTitle(R.string.shopping_delete_list)
            .setMessage(getString(R.string.shopping_delete_list_message, list.name))
            .setNegativeButton(android.R.string.cancel, null)
            .setPositiveButton(R.string.product_delete) { _, _ ->
                viewLifecycleOwner.lifecycleScope.launch {
                    KeeplyDatabase.getInstance(requireContext())
                        .shoppingListDao()
                        .deleteById(list.id)
                    Toast.makeText(requireContext(), R.string.shopping_deleted, Toast.LENGTH_SHORT)
                        .show()
                }
            }
            .show()
    }

    companion object {
        const val TAG = "ShoppingListsFragment"
        private const val ARG_OPEN_AUTO = "arg_open_auto"

        fun newInstance(openAutoDialog: Boolean = false): ShoppingListsFragment {
            return ShoppingListsFragment().apply {
                arguments = Bundle().apply { putBoolean(ARG_OPEN_AUTO, openAutoDialog) }
            }
        }
    }
}
